config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do



    resources :passwords, controller: "clearance/passwords", only: [:create, :new]
    resource :session, controller: "sessions", only: [:create]

    # users resources
    resources :users, controller: 'users', only: [:index, :show, :edit, :update]
    resources :users, controller: "users", only: [:create] do
        resource :password,
                 controller: "clearance/passwords",
                 only: [:create, :edit, :update]
        resources :listings, except: [:destroy]
    end


    get '/listings/search' => 'listings#search', as: :search_listings

    # listings resources
    resources :listings, only: [:index, :show] do
        resources :reservations

        member do
            get 'verify/edit' => 'listings#edit_by_moderator', as: :edit_by_moderator
            # patch 'verify' => 'listings#update_verified', as: :update_verify
        end
    end



    # reservations resources
    post '/reservations/:reservation_id/payments' => 'payments#checkout', as: :reservation_check_out

    # this path for email testing only
    # get '/reservations/email' => 'reservations#send_email', as: :reservation_email

    resources :reservations do
        resources :payments
    end

    delete '/users/:user_id/listings/:id' => 'listings#destroy', as: :delete_user_listing


    root 'static#index'

    ####### AUTHENTICATION
    post "/sign_in" => "sessions#create", as: "sign_in"
    delete "/sign_out" => "sessions#destroy", as: "sign_out"
    post "/sign_up" => "users#new", as: "sign_up"
    get "/auth/:provider/callback" => "sessions#create_from_omniauth"
    ####### AUTHENTICATION END



    mount Sidekiq::Web, at: "/sidekiq"

end

app/models/listing.rb
class Listing < ApplicationRecord
    belongs_to :user
    belongs_to :location
    has_many :reservations

    mount_uploaders :images, ImagesUploader

    def self.verified
        where('verified = ?', true)
    end

    def self.not_verified
        where('verified = ?', false)
    end

    def self.search_by(param:{})
        city = param.fetch('city', '')

        check_in = param.fetch('check_in',Date.new(1980, 1 ,1))
        check_out = param.fetch('check_out', Date.new(1980, 1, 1))

        # swap check in and check out date
        if check_in > check_out
            temp = check_in
            check_in = check_out
            check_out = temp
        end

        reserved_listings_id =  self.get_reserved_listings_id(check_in, check_out)

        if reserved_listings_id.blank?
            # return id as -1 so that any listings would fulfil this criteria
            reserved_listings_id = [-1]
        end

        verified.left_outer_joins(:location).where('locations.city ilike ? and listings.id not in (?)', "%#{city}%", reserved_listings_id)
    end

    def self.get_reserved_listings_id(check_in, check_out)
        Reservation.where('not (check_in >= ? or check_out <= ?)', check_out, check_in).pluck(:listing_id)
    end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    include ListingsHelper

    before_action(except: [:show, :index, :search]) do
        not_sign_in_redirect url: listings_path, msg: 'Please sign in to perform this action'
    end

    before_action(except: [:index, :new, :create, :search]) do
        resource_exist? url: listings_path, resource: Listing, resource_id: params[:id], msg: 'There is no such listing'
    end

    before_action(only: [:edit]) do
        continue = is_moderator? url: edit_by_moderator_listing_path, msg: 'Entering moderator editing mode'

        if continue
            belongs_to_current_user? url: listing_path(params[:id]), resource: Listing, resource_id: params[:id], msg: "You can only edit your own listing"
        end
    end

    before_action(only: [:update, :destroy]) do

        if !current_user.moderator?
            belongs_to_current_user? url: listing_path(params[:id]), resource: Listing, resource_id: params[:id], msg: "You can only edit your own listing"
        end
    end



    def index
        @is_host = false
        @listings = listings_by_role
        if params.keys.include? 'user_id'
            @is_host = true
        end
        render 'listings/index'
    end

    def new
        @listing = Listing.new
        @locations = Location.all
        @avoid_footer = 'avoid-footer'
        render 'listings/new'
    end

    def create
        new_listing = current_user.listings.new(listing_params)
        @avoid_footer = 'avoid-footer'
        if new_listing.save
            redirect_to listing_path(new_listing)
        else
            new_listing.errors.messages
        end
    end

    def show
        @listing = Listing.includes(:location).find(params[:id])
    end

    def search
        @permitted_params = listings_search_params.to_h

        if @permitted_params["check_in"].blank? or @permitted_params["check_out"].blank?
            @listings = listings_by_role
            flash[:notice] = ['Please key in appropriate to search for listings.']
        else
            @listings = Listing.search_by(param: @permitted_params).paginate(page:params[:page], per_page: 3)
        end

        return render 'listings/index'


    end

    def edit
        @listing = current_user.listings.find(params[:id])
        # todo what if the listing has been deleted
        @locations = Location.all
    end

    def edit_by_moderator
        @listing = Listing.find(params[:id])
        @locations = Location.all
        render 'edit'
    end

    def update
        @listing = Listing.find(params[:id])
        if current_user.moderator?
            role_params = moderator_params
        else
            role_params = listing_params.except([:user_id, :verified])
            role_params['verified'] = yes_no_to_boolean(role_params['verified'])
        end
        @listing.update_attributes(role_params)
        if @listing.save
            flash[:notice] = 'You have editted this listing'
        else
            flash[:notice] = @listing.errors.messages
        end

        redirect_to @listing
    end



    def destroy
        if !params[:user_id].nil?
            listing = Listing.find(params[:id])
            listing.destroy
            return redirect_to current_user, notice: 'The listing has been deleted!'
        end
    end

    private

    def supported_search_param
        ['city', 'check_in', 'check_out']
    end

    def listing_params
        params.require(:listing).permit([:name, :location_id, :person_count, :base_price, :smoke, :pet, :user_id, :room_count, {images:[]}])
    end

    def moderator_params
        params.require(:listing).permit([:verified])
    end

    def listings_search_params
        params.permit(:city, :check_in, :check_out)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper

    # CONTROLLER HELPER METHOD
    def listings_by_role
        if !signed_in?
            return Listing.verified.order('updated_at desc').paginate(page:params[:page], per_page: 3)
        end

        if current_user.customer?
            if params.keys.include? 'user_id'
            #     populate listings for host
                return current_user.listings.order('updated_at desc').paginate(page:params[:page], per_page: 3)
            else
            #     populate listings for travel
                return Listing.verified.order('updated_at desc').paginate(page:params[:page], per_page: 3)
            end
        else
            # listings for moderator
            return Listing.not_verified.paginate(page:params[:page], per_page: 3)
        end

    end

    # VIEW HELPER METHOD

    def line_through_class(yes_or_no)
        if yes_or_no == 'Y' or yes_or_no == true
            ''
        else
            'allowed'
        end
    end

    def yes_no_to_boolean(yes_or_no)
        if yes_or_no == 'Y'
            true
        else
            false
        end
    end

    def boolean_to_yes_no(boolean)
        if boolean
            'Y'
        else
            'N'
        end
    end


end

app/views/listings/_listing_cards.html.haml
- @avoid_footer||=''

#listings-card.card-deck.listing-card-deck
    .row.listing-pagination
        -# todo beautify the pagination later
        .apple_pagination
            = will_paginate @listings, previous_label: '&laquo;', next_label:'&raquo;'
    .row.mt-sm-1{class: - @avoid_footer}
        - @listings.each do |listing|
            .col-md-4.px-0.my-sm-1
                = link_to listing_path(listing) do
                    .card.rounded-0.mx-sm-1.mx-sm-1.border-0
                        - if listing.images.size == 0
                            %img.card-img-top.rounded-0{:alt => listing.name, :src => image_url('listing_sample_cover.jpg')}
                        - else
                            %img.card-img-top.rounded-0{:alt => listing.name, :src => image_url(listing.images[0].url)}
                        .card-body.py-sm-1
                            %p.card-text.font-weight-bold.mb-sm-1
                                = "RM#{listing.base_price.to_i} #{listing.name}"
                            %p.card-text
                                = "Accomodate #{listing.person_count} people"
                        .card-footer.p-sm-1
                            - class_hash = {"Y"=>"badge-dark", "N"=>"badge-secondary"}
                            - smoke_badge = class_hash[listing.smoke]
                            - pet_badge = class_hash[listing.pet]
                            %span.badge.badge-pill.align-middle{class: smoke_badge} Smoke
                            %span.badge.badge-pill.align-middle{class: pet_badge} Pet

app/views/listings/_new_listing_form.html.haml
= form_for @listing, url: test_path do |f|
    = f.label :name

app/views/listings/_search_form.html.haml
- @permitted_params||={}
.row
    .col-md-8
        = form_tag({controller: 'listings', action: 'search'}, method: 'get', class: 'form-row col-md-12') do
            .col-md-3
                = text_field_tag 'city', nil, placeholder: 'city', value: @permitted_params.fetch("city", ''), class: 'form-control'
            .col-md-3
                = text_field_tag 'check_in', nil, id:'reservation_check_in', value: @permitted_params.fetch('check_in', ''), class: 'form-control'
            .col-md-3
                = text_field_tag 'check_out', nil, id:'reservation_check_out', value: @permitted_params.fetch('check_out', ''), class: 'form-control'
            .col-md-3
                %button{class: 'btn btn-primary w-100', type: 'submit', role: 'button'} Search
                -#= submit_tag 'Submit', class: 'btn btn-primary w-100', role: 'button'

app/views/listings/edit.html.haml
= form_for [current_user, @listing], method: :patch, html:{class:"p-2"} do |f|
    - label_class = 'col-sm-2'
    - value_class = 'col-sm-4'
    - value_class_half = 'col-md-2'

    .form-group.row
        = f.label :name, class:label_class
        = f.text_field :name, class:"#{value_class} form-control", value: @listing.name
    .form-group.row
        = f.label :location, class:"#{label_class}", for: "location_id"
        %select.form-control{name:'listing[location_id]', id:"location_id", class: - value_class}
            - @locations.each do |loc|
                - selected = true if loc.id == @listing.location_id || false
                %option{value: loc.id, selected: selected}
                    = "#{loc.state} | #{loc.city}"
    .form-group.row
        = f.label :room_count, class:label_class, for: "room_count_id"
        %select.form-control{name:'listing[room_count]', id:"room_count_id", class: - value_class}
            - (1..10).each do |i|
                - selected = true if i == @listing.room_count || false
                %option{value: i, selected: selected}
                    = "#{i} rooms"
    .form-group.row
        = f.label :person_count, class:label_class, for: 'person_count'
        %select.form-control{name:'listing[person_count]', id:"person_count", class: - value_class}
            - (1..12).each do |i|
                - selected = true if @listing.person_count == i || false
                %option{value: i, selected: selected}
                    = "#{i} person"
    .form-group.row
        = f.label :base_price, class:label_class
        = f.text_field :base_price, class: "#{value_class} form-control", value: @listing.base_price
    -# smoke here
    .form-group.row
        = f.label :smoke, class: label_class
        %select.form-control{name:"listing[smoke]", class: - value_class}
            - ["Y", "N"].each do |choice|
                - selected = true if @listing.smoke == choice || false
                %option{value: choice, selected: selected}
                    = choice
    -# pet here
    .form-group.row
        = f.label :pet, class: label_class
        %select.form-control{name:"listing[pet]", class: - value_class}
            - ["Y", "N"].each do |choice|
                - selected = true if @listing.pet == choice || false
                %option{value: choice, selected: selected}
                    = choice
    -# moderator verify here
    - if current_user.moderator?
        .form-group.row
            = f.label :verified, class: label_class
            %select.form-control{name:"listing[verified", class: - value_class}
                - ["Y", "N"].each do |choice|
                    - selected = true if boolean_to_yes_no(@listing.verified) == choice || false
                    %option{value: choice, selected: selected}
                        =choice
    .form-group.row
        = f.label :images, class: label_class
        = f.file_field :images, multiple: true
    .form-group.row
        %div{class: 'col-sm-3'}
            %button.btn.btn-primary.w-100.mb-2.mb-md-0{ type: 'submit'} Submit
        %div{class: 'col-sm-3'}
            %a.btn.btn-secondary.w-100{href: listing_path(@listing), role:'button'} Cancel

app/views/listings/index.html.haml
- @is_host ||= false

- if @is_host
    %h2.row.lead
        = "Showing your listings..."
    .row
        .col-sm-2.p-0
            %a.btn.btn-primary{href:new_user_listing_path(current_user), role: 'button'}
                New listing
- else
    = render partial: 'listings/search_form'
%hr
= render partial: 'listings/listing_cards'

app/views/listings/new.html.haml
= form_for [current_user, Listing.new] do |f|
    - label_class = 'col-sm-2'
    - value_class = 'col-sm-4'
    - half_value_class = 'col-sm-2'
    .form-group.row.mx-0
        = f.label :name, class:"#{label_class}"
        = f.text_field :name, class:"#{value_class} form-control", placeholder: 'Name of your property'
    .form-group.row.mx-0
        = f.label :location, class:label_class, for: "location_id"
        %select.form-control{name:'listing[location_id]', id:"location_id", class: - value_class}
            - @locations.each do |loc|
                %option{value: loc.id}
                    = "#{loc.state} | #{loc.city}"
    .form-group.row.mx-0
        = f.label :person_count, class:label_class, for: 'person_count'
        %select.form-control{name:'listing[person_count]', id:"person_count", class: - value_class}
            - (1..12).each do |i|
                %option{value: i}
                    = "#{i} person"
    .form-group.row.mx-0
        = f.label :base_price, class:label_class
        = f.text_field :base_price, class:"#{value_class} form-control", placeholder: 'Base price per night'
    -# smoke here
    .form-group.row.mx-0
        = f.label :smoke, class: label_class
        %select.form-control{name:"listing[smoke]", class: - value_class}
            %option{value: "Y"}
                Y
            %option{value: "N"}
                N
    -# pet here
    .form-group.row.mx-0
        = f.label :pet, class: label_class
        %select.form-control{name:"listing[pet]", class: - value_class}
            %option{value: "Y"}
                Y
            %option{value: "N"}
                N
    .form-group.row.mx-0
        = f.label :images, class: label_class
        = f.file_field :images, multiple: true
    .form-group.row
        .col-sm-2
        .col-sm-2
            %button.btn.btn-primary.w-100.mb-md-0.mb-2{type: 'submit'} Submit
        .col-sm-2
            %a.btn.btn-secondary.w-100{href: user_listings_path(current_user), role: 'button'} Cancel

app/views/listings/show.html.haml
#carouselListing.carousel.slide{"data-ride" => "carousel"}
    %ol.carousel-indicators
        -# todo insert the image count here
        %li.active{"data-slide-to" => "0", "data-target" => "#carouselListing"}
    .carousel-inner
        -# todo insert the image url here
        .carousel-item.active
            - if @listing.images.size == 0
                %img.d-block.w-100{:alt => "First slide", :src => "..."}
            - else
                %img.d-block.w-100{alt: 'listing image', :src => image_url(@listing.images[0].url)}
        - if @listing.images.size > 1
            - (1...@listing.images.size).each do |i|
                .carousel-item
                    %img.d-block.w-100{alt: 'listing image', src: image_url(@listing.images[i].url)}
    %a.carousel-control-prev{"data-slide" => "prev", :href => "#carouselListing", :role => "button"}
        %span.carousel-control-prev-icon{"aria-hidden" => "true"}
        %span.sr-only Previous
    %a.carousel-control-next{"data-slide" => "next", :href => "#carouselListing", :role => "button"}
        %span.carousel-control-next-icon{"aria-hidden" => "true"}
        %span.sr-only Next

%hr
.listing-info
    .row.listing-control
        .col-sm-8
            .row
                - if current_user.id == @listing.user_id or current_user.moderator?
                    .col-sm-4.col-lg-3.col-4.p-1
                        = button_to 'Edit', edit_user_listing_path(current_user, @listing), method: :get,
                        form_class: 'form-inline',class: "btn btn-primary w-100", role: 'button'
                - if current_user.id == @listing.user_id
                    .col-sm-4.col-lg-3.col-4.p-1
                        = link_to 'Reservations', listing_reservations_path(@listing),
                        class: 'btn btn-primary w-100', role: 'button'
                    .col-sm-4.col-lg-3.col-4.p-1
                        = button_to 'Remove', delete_user_listing_path(@listing), method: :delete,
                         form_class: 'form-inline', class: 'btn btn-danger w-100',
                         role:'button', data:{confirm:'Do you want to remove this listing?'}
    .row
        .col.listing-info.col-sm-6
            .row.listing-title
                .col-sm-12
                    %h2
                        = @listing.name
                    %p.lead
                        = "#{@listing.location.city}, #{@listing.location.state}, #{@listing.location.country}"
                    %hr
            .row.listing-details
                .col-sm-12
                    %h5
                        The Space
                    .row
                        .col-sm-6
                            .row.mx-0
                                %span
                                    = "Accomodates:"
                                %span.font-weight-bold
                                    = @listing.person_count
                            .row.mx-0
                                %span
                                    = "Rooms: "
                                %span.font-weight-bold
                                    = @listing.room_count
                    %hr.my-1
            .row.listing-details
                .col-sm-12
                    %h5
                        The Price
                    .row
                        .col-sm-6
                            .row.mx-0
                                %span
                                    = "Base price:"
                                %span.font-weight-bold
                                    = "RM #{@listing.base_price.to_i}"
                    %hr.my-1
            .row.listing-details
                .col-sm-12
                    %h5
                        The Amenities
                    .row
                        .col-sm-6
                            .row{class: - "#{line_through_class(@listing.pet)} mx-0"}
                                = "Pet allowed"
                            .row{class: - "#{line_through_class(@listing.smoke)} mx-0"}
                                = "Smoking allowed"
        .col-sm-6.reservation-form
            -# show the reservation booking form
            - if @listing.user_id != current_user.id
                = render partial: 'reservations/new'