config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do



    resources :passwords, controller: "clearance/passwords", only: [:create, :new]
    resource :session, controller: "sessions", only: [:create]

    # users resources
    resources :users, controller: 'users', only: [:index, :show, :edit, :update]
    resources :users, controller: "users", only: [:create] do
        resource :password,
                 controller: "clearance/passwords",
                 only: [:create, :edit, :update]
        resources :listings, except: [:destroy]
    end


    get '/listings/search' => 'listings#search', as: :search_listings

    # listings resources
    resources :listings, only: [:index, :show] do
        resources :reservations

        member do
            get 'verify/edit' => 'listings#edit_by_moderator', as: :edit_by_moderator
            # patch 'verify' => 'listings#update_verified', as: :update_verify
        end
    end



    # reservations resources
    post '/reservations/:reservation_id/payments' => 'payments#checkout', as: :reservation_check_out

    # this path for email testing only
    # get '/reservations/email' => 'reservations#send_email', as: :reservation_email

    resources :reservations do
        resources :payments
    end

    delete '/users/:user_id/listings/:id' => 'listings#destroy', as: :delete_user_listing


    root 'static#index'

    ####### AUTHENTICATION
    post "/sign_in" => "sessions#create", as: "sign_in"
    delete "/sign_out" => "sessions#destroy", as: "sign_out"
    post "/sign_up" => "users#new", as: "sign_up"
    get "/auth/:provider/callback" => "sessions#create_from_omniauth"
    ####### AUTHENTICATION END



    mount Sidekiq::Web, at: "/sidekiq"

end

app/models/user.rb
class User < ApplicationRecord
    include Clearance::User
    validates :name, presence: true, length: {maximum: 50}

    has_many :authentications
    has_many :listings
    has_many :reservations

    enum role:[:customer, :moderator, :admin]

    mount_uploader :avatar, AvatarUploader

    def self.create_with_auth_and_hash(authentication, auth_hash)
        user = self.create!(
           name: auth_hash['info']['name'],
           email: auth_hash['info']['email'],
           password: SecureRandom.hex(10)
        )
        user.authentications << authentication
        return user
    end

    def get_listings_reservations
        listings_ids = self.listings.pluck(:id)
        Reservation.where("listing_id in (?)", listings_ids)
    end

    # grab fb_token to access Facebook for user data
    def fb_token
        x = self.authentications.find_by(provider: 'facebook')
        return x.token unless x.nil?
    end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
    before_action(only: [:show, :edit, :update, :destroy]) do
        not_sign_in_redirect url: root_path, msg: 'Please sign in to perform this action'
    end

    def new
        @user = User.new
        render "users/new"
    end

    def create
        @user = User.new user_params

        if @user.save
            sign_in @user
            redirect_back_or url_after_create
        else
            render template: "users/new"
        end
    end

    def show
        @user = User.find(params[:id])
        if @user.reservations.exists?
            @days_to_check_in = (Date.today - @user.reservations.check_in_from_today.first.check_in).to_i
        end

        if @user.get_listings_reservations.check_in_from_today.exists?
            @days_to_guest_check_in = (Date.today - @user.get_listings_reservations.check_in_from_today.first.check_in).to_i
        end
        @listings = @user.listings.order('updated_at DESC').paginate(page: params[:page], per_page: 3)
        @avoid_footer = 'avoid-footer'
        render 'show'
    end

    def edit

    end

    def update
        not_sign_in_redirect msg: 'Please sign in to perform this action'

        @user = User.find(params[:id])

        if user_params[:avatar].nil?
            @user.update_attributes user_params.except([:email, :avatar])
        else
            @user.update_attributes user_params.except(:email)
        end
        if @user.save
            redirect_to user_path(current_user)
            return
        else
            redirect_to edit_user_path(current_user)
            return
        end
    end


    def user_params
        params.require(:user).permit(:email, :name, :state, :country, :password, :avatar)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
= form_for current_user, action: users_path(current_user), method: :patch, html:{class:"p-md-0 p-3"}  do |f|
    - label_class = 'col-sm-2'
    - value_class = 'col-sm-4'
    .form-group.row
        = f.label :name, class:label_class
        = f.text_field :name, class:"#{value_class} form-control", value: current_user.name
    .form-group.row
        = f.label :email, class:label_class
        = f.text_field :email, class:"#{value_class} form-control", value: current_user.email, readonly: true
    .form-group.row
        = f.label :state, class:label_class
        = f.text_field :state, class:"#{value_class} form-control", value: current_user.state
    .form-group.row
        = f.label :country, class:label_class
        = f.text_field :country, class:"#{value_class} form-control", value: current_user.country
    .form-group.row
        = f.label :avatar, class: label_class
        = f.file_field :avatar, class:"#{value_class}"
    .form-group.row
        .col-sm-2
        .col-sm-2
            %button.btn.btn-primary.w-100.mb-1.mb-md-0{ type: 'submit'} Submit
        .col-sm-2
            %a.btn.btn-secondary.w-100{ href:user_path(current_user), role:'button'} Cancel
            -#= button_to 'Cancel', users_path(current_user), method: :get, action: 'show',
            -#html: {class: 'btn btn-secondary w-100', role: 'button', type: 'button'}

app/views/users/new.html.haml
= form_for @user, url:@user, method: 'post' do |f|
    = f.label :name, class:''
    = f.text_field :name
    %br
    = f.label :name
    = f.text_field :email
    %br
    = f.label :password
    = f.text_field :password, type: 'password'
    %br
    = f.label :state
    = f.text_field :state
    %br
    = f.label :country
    = f.text_field :country
    %br
    = f.submit 'Submit'

app/views/users/show.html.haml
.jumbotron
    %h1.display-3
        = "Hello, #{@user.name}"
    %p.lead
        - if @days_to_check_in
            = "Your next trip is #{@days_to_check_in} days from today! Get ready for the trip!"
        - else
            = "You don't have any reservation. Plan for your next travel now!"
    %hr.my-4.jumbotron-seperator
    %p.lead
        - if @days_to_guest_check_in
            = "You have guest check in in #{@days_to_guest_check_in} from today!"
        - else
            = "You don't have any reservation coming forward."
    = button_to 'Edit profile', edit_user_path(current_user.id), method: :get, class: "btn btn-primary", role: "button"