config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do



    resources :passwords, controller: "clearance/passwords", only: [:create, :new]
    resource :session, controller: "sessions", only: [:create]

    # users resources
    resources :users, controller: 'users', only: [:index, :show, :edit, :update]
    resources :users, controller: "users", only: [:create] do
        resource :password,
                 controller: "clearance/passwords",
                 only: [:create, :edit, :update]
        resources :listings, except: [:destroy]
    end


    get '/listings/search' => 'listings#search', as: :search_listings

    # listings resources
    resources :listings, only: [:index, :show] do
        resources :reservations

        member do
            get 'verify/edit' => 'listings#edit_by_moderator', as: :edit_by_moderator
            # patch 'verify' => 'listings#update_verified', as: :update_verify
        end
    end



    # reservations resources
    post '/reservations/:reservation_id/payments' => 'payments#checkout', as: :reservation_check_out

    # this path for email testing only
    # get '/reservations/email' => 'reservations#send_email', as: :reservation_email

    resources :reservations do
        resources :payments
    end

    delete '/users/:user_id/listings/:id' => 'listings#destroy', as: :delete_user_listing


    root 'static#index'

    ####### AUTHENTICATION
    post "/sign_in" => "sessions#create", as: "sign_in"
    delete "/sign_out" => "sessions#destroy", as: "sign_out"
    post "/sign_up" => "users#new", as: "sign_up"
    get "/auth/:provider/callback" => "sessions#create_from_omniauth"
    ####### AUTHENTICATION END



    mount Sidekiq::Web, at: "/sidekiq"

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    def new
        @reservation = Reservation.find(params[:reservation_id])
        @client_token = Braintree::ClientToken.generate
    end

    def checkout

        # check availability
        reservation = Reservation.find(params[:reservation_id])
        if !reservation.available_to_book?
            flash[:notice] = 'The requested date has been booked. Please try other date.'
            reservation.destroy
            return redirect_to listing_path(reservation.listing_id)
        end

        nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

        # submit payment process request to braintree
        result = Braintree::Transaction.sale(
                :amount => reservation.price,
                :payment_method_nonce => nonce_from_the_client,
                :options => {
                        :submit_for_settlement => true
                }
        )

        if result.success?
            # UserMailer.reservation_confirmation(reservation_id).deliver_later
            ReservationJob.set(wait: 1.minute).perform_later reservation.id
            redirect_to reservations_path, :flash => { :notice => "Transaction successful!" }
        else
            # todo handle payment failure
            redirect_to listing_path(reservation.listing_id), :flash => { :notice => "Transaction failed. Please try again." }
        end
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/new.html.haml
.payment-form#payment-form
    .lead.amount
        = "Payment amount: #{@reservation.price}"
    = form_for :checkout_form, url: reservation_check_out_path(@reservation.id), html: { id: 'cardForm' } do |f|
        = f.label :card_number, 'Credit Card Number', class: 'hosted-fields--label'
        #card-number.hosted-field

        = f.label :expiration_date, 'Expiration Date', class: 'hosted-fields--label'
        #expiration-date.hosted-field

        = f.label :cvv, 'CVV', class: 'hosted-fields--label'
        #cvv.hosted-field

        = f.hidden_field 'payment_method_nonce'
        .row
            .col-md-3
                .button-container
                    = f.submit 'Pay', disabled: true, class: 'btn btn-primary w-100', id: 'submit-payment-btn'

%script{src: "https://js.braintreegateway.com/web/3.22.2/js/client.js"}
%script{src: "https://js.braintreegateway.com/web/3.22.2/js/hosted-fields.js"}

:javascript
    var form = document.querySelector('#cardForm');
    var submit = document.querySelector('#submit-payment-btn');

    braintree.client.create({
        authorization: '#{@client_token}'
    }, function (clientErr, clientInstance) {
        if (clientErr) {
            console.error(clientErr);
            return;
        }

        // This example shows Hosted Fields, but you can also use this
        // client instance to create additional components here, such as
        // PayPal or Data Collector.

        braintree.hostedFields.create({
            client: clientInstance,
            styles: {
                'input': {
                    'font-size': '14px'
                },
                'input.invalid': {
                    'color': 'red'
                },
                'input.valid': {
                    'color': 'green'
                }
            },
            fields: {
                number: {
                    selector: '#card-number',
                    placeholder: '4111 1111 1111 1111'
                },
                cvv: {
                    selector: '#cvv',
                    placeholder: '123'
                },
                expirationDate: {
                    selector: '#expiration-date',
                    placeholder: '10/2019'
                }
            }
        }, function (hostedFieldsErr, hostedFieldsInstance) {
            if (hostedFieldsErr) {
                console.error(hostedFieldsErr);
                return;
            }

            submit.removeAttribute('disabled');

            form.addEventListener('submit', function (event) {
                event.preventDefault();

                hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
                    if (tokenizeErr) {
                        console.error(tokenizeErr);
                        return;
                    }
                    document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
                    // If this was a real integration, this is where you would
                    // send the nonce to your server.
                    console.log('Got a nonce: ' + payload.nonce);

                    form.submit();
                });
            }, false);
        });
    });