config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do



    resources :passwords, controller: "clearance/passwords", only: [:create, :new]
    resource :session, controller: "sessions", only: [:create]

    # users resources
    resources :users, controller: 'users', only: [:index, :show, :edit, :update]
    resources :users, controller: "users", only: [:create] do
        resource :password,
                 controller: "clearance/passwords",
                 only: [:create, :edit, :update]
        resources :listings, except: [:destroy]
    end


    get '/listings/search' => 'listings#search', as: :search_listings

    # listings resources
    resources :listings, only: [:index, :show] do
        resources :reservations

        member do
            get 'verify/edit' => 'listings#edit_by_moderator', as: :edit_by_moderator
            # patch 'verify' => 'listings#update_verified', as: :update_verify
        end
    end



    # reservations resources
    post '/reservations/:reservation_id/payments' => 'payments#checkout', as: :reservation_check_out

    # this path for email testing only
    # get '/reservations/email' => 'reservations#send_email', as: :reservation_email

    resources :reservations do
        resources :payments
    end

    delete '/users/:user_id/listings/:id' => 'listings#destroy', as: :delete_user_listing


    root 'static#index'

    ####### AUTHENTICATION
    post "/sign_in" => "sessions#create", as: "sign_in"
    delete "/sign_out" => "sessions#destroy", as: "sign_out"
    post "/sign_up" => "users#new", as: "sign_up"
    get "/auth/:provider/callback" => "sessions#create_from_omniauth"
    ####### AUTHENTICATION END



    mount Sidekiq::Web, at: "/sidekiq"

end

app/views/layouts/_navbar.html.haml
%nav#header-navbar.navbar.navbar-expand-md.navbar-light
    %a.navbar-brand{:href => root_path} Pairbnb
    %button.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNav", "data-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
    #navbarNav.collapse.navbar-collapse
        %ul.navbar-nav.mr-md-auto
            %li.nav-item.active
                %a.nav-link{:href => root_path}
                    Home
                    %span.sr-only (current)
            - if current_user.nil?
                %li.nav-item
                    %a.nav-link{href:'#signin-modal', 'data-toggle'=>"modal", 'data-target'=>'#signin-modal'} Sign In
                %li.nav-item
                    %a.nav-link{href:'#signup-modal', 'data-toggle'=>'modal', 'data-target'=>'#signup-modal'} Sign Up
            %li.nav-item
                %a.nav-link{href:'#'} About Us
        %ul.navbar-nav
            - if current_user
                %li#user-avatar.nav-item
                    %img.rounded-circle{src: current_user.avatar}
                %li.dropdown.nav-item
                    %a.dropdown-toggle.nav-link{href: '#', "data-toggle":"dropdown"}
                        = current_user.name
                    .dropdown-menu
                        = link_to 'Profile', user_path(current_user), class: 'dropdown-item'
                        .dropdown-divider
                        = link_to 'Listings', user_listings_path(current_user), class: 'dropdown-item'
                        = link_to 'Reservations', reservations_path, class: 'dropdown-item'
                -#%li#user-link.nav-item
                -#    = link_to current_user.name, user_path(current_user), class:'nav-link'
                %li.nav-item
                    = link_to 'Sign out', sign_out_path, method: :delete, class:'nav-link'

app/views/layouts/application.html.haml
%html
    %head
        %title Pairbnb
        %meta{name:"viewport", content:"width=device-width, initial-scale=1.0"}
        -#= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'
        = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
        = javascript_include_tag 'application', 'data-turbolinks-track' => true
        = csrf_meta_tags
        %link{href:'https://fonts.googleapis.com/css?family=Open+Sans', rel:'stylesheet', type:'text/css'}


    %body
        - if flash[:notice]
            = render partial: 'utility/flash'
        = render partial: 'layouts/navbar'
        %div.container
            = yield

        -# some modals for user to interact with users
        = render partial: 'utility/login_alert_modal'
        = render partial: 'utility/signin_modal'
        = render partial: 'utility/signup_modal'

        -# todo fix the position of the footer
        %footer#footer.footer.mt-2
            %div.container
            %nav.nav
                %a.nav-link About Us
                %a.nav-link Privacy
                %a.nav-link Terms
                %a.nav-link Contact Us
                %a.nav-link Signup for newsletter